export const CONFIG_SET_FLAVOR = 'CONFIG_SET_FLAVOR';

export const COURIER_SET_PROFILE = 'COURIER_SET_PROFILE';
export const COURIER_UPDATE_STATUS = 'COURIER_UPDATE_STATUS';
export const COURIER_UPDATE_LOCATION = 'COURIER_UPDATE_LOCATION';
export const COURIER_UPDATE_VISIBLE_COURIERS = 'COURIER_UPDATE_VISIBLE_COURIERS';