export const CONFIG_SET_FLAVOR = 'CONFIG_SET_FLAVOR';

// set locally
export const SET_COURIER_PROFILE = 'SET_COURIER_PROFILE';
export const SET_LOCATION = 'SET_LOCATION';
// receive updates from backend
export const COURIER_PROFILE_UPDATED = 'COURIER_PROFILE_UPDATED';
export const AVAILABLE_COURIERS_UPDATED = 'AVAILABLE_COURIERS_UPDATED';